// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ContactItem: typeof import('./src/components/contact/ContactItem.vue')['default']
    ContactList: typeof import('./src/components/contact/ContactList.vue')['default']
    ContentHeader: typeof import('./src/components/ContentHeader.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Home: typeof import('./src/components/Home.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    MessageCell: typeof import('./src/components/message/MessageCell.vue')['default']
    MessageItem: typeof import('./src/components/message/MessageItem.vue')['default']
    MessageList: typeof import('./src/components/message/MessageList.vue')['default']
    NewContactItem: typeof import('./src/components/contact/NewContactItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchItem: typeof import('./src/components/Search/SearchItem.vue')['default']
    SearchList: typeof import('./src/components/Search/SearchList.vue')['default']
    SettingItem: typeof import('./src/components/Setting/SettingItem.vue')['default']
    SettingList: typeof import('./src/components/Setting/SettingList.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
  }
}
